definitions:
  models.JSONResult:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/employees:
    get:
      consumes:
      - application/json
      description: 取得員工列表
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得員工列表
      tags:
      - 員工
    post:
      consumes:
      - application/json
      description: 新增員工
      parameters:
      - description: 員工編號
        in: body
        name: employee_number
        required: true
        schema:
          type: string
      - description: 員工名稱
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 新增員工
      tags:
      - 員工
  /api/v1/employees/{id}:
    delete:
      consumes:
      - application/json
      description: 刪除員工
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 刪除員工
      tags:
      - 員工
    get:
      consumes:
      - application/json
      description: 取得員工資料
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得員工資料
      tags:
      - 員工
    put:
      consumes:
      - application/json
      description: 更新員工資料
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 員工名稱
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 更新員工資料
      tags:
      - 員工
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: 取得用戶列表
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得用戶列表
      tags:
      - 用戶
    post:
      consumes:
      - application/json
      description: 新增用戶
      parameters:
      - description: 用戶名稱
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 會員密碼
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 會員角色
        in: body
        name: roles
        required: true
        schema:
          type: string
      - description: 用戶真實名稱
        in: body
        name: real_name
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 新增用戶
      tags:
      - 用戶
  /api/v1/users/{id}:
    delete:
      consumes:
      - application/json
      description: 刪除用戶
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 刪除用戶
      tags:
      - 用戶
    get:
      consumes:
      - application/json
      description: 取得用戶資料
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得用戶資料
      tags:
      - 用戶
    put:
      consumes:
      - application/json
      description: 更新用戶資料
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 用戶名稱
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 會員密碼
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 會員角色
        in: body
        name: roles
        required: true
        schema:
          type: string
      - description: 用戶真實名稱
        in: body
        name: real_name
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 更新用戶資料
      tags:
      - 用戶
  /api/v1/vip-shopping-records:
    get:
      consumes:
      - application/json
      description: 取得扣款記錄列表
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得扣款記錄列表
      tags:
      - 扣款記錄
  /api/v1/vip-shopping-records/{id}:
    get:
      consumes:
      - application/json
      description: 取得扣款記錄資料
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得扣款記錄資料
      tags:
      - 扣款記錄
  /api/v1/vip-stored-records:
    get:
      consumes:
      - application/json
      description: 取得儲值記錄列表
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得儲值記錄列表
      tags:
      - 儲值記錄
  /api/v1/vip-stored-records/{id}:
    get:
      consumes:
      - application/json
      description: 取得儲值記錄資料
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得儲值記錄資料
      tags:
      - 儲值記錄
  /api/v1/vips:
    get:
      consumes:
      - application/json
      description: 取得會員列表
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得會員列表
      tags:
      - 會員
    post:
      consumes:
      - application/json
      description: 新增會員
      parameters:
      - description: 會員帳號
        in: body
        name: account
        required: true
        schema:
          type: string
      - description: 會員名稱
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 會員密碼
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 會員角色
        in: body
        name: roles
        required: true
        schema:
          type: string
      - description: 會員真實名稱
        in: body
        name: real_name
        schema:
          type: string
      - description: 會員性別
        in: body
        name: gender
        schema:
          type: string
      - description: 會員生日
        in: body
        name: birthday
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 新增會員
      tags:
      - 會員
  /api/v1/vips-id/{vid}/start/{start}/end/{end}/shopping-records:
    get:
      consumes:
      - application/json
      description: 用會員 ID 及日期區間取得扣款記錄資料
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 用會員 ID 及日期區間取得扣款記錄資料
      tags:
      - 扣款記錄
  /api/v1/vips-id/{vid}/start/{start}/end/{end}/stored-records:
    get:
      consumes:
      - application/json
      description: 用會員 ID 及日期區間取得儲值記錄資料
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 用會員 ID 及日期區間取得儲值記錄資料
      tags:
      - 儲值記錄
  /api/v1/vips/{id}:
    delete:
      consumes:
      - application/json
      description: 刪除會員
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 刪除會員
      tags:
      - 會員
    get:
      consumes:
      - application/json
      description: 取得會員資料
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 取得會員資料
      tags:
      - 會員
    put:
      consumes:
      - application/json
      description: 更新會員資料
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 會員密碼
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 會員角色
        in: body
        name: roles
        required: true
        schema:
          type: string
      - description: 會員真實名稱
        in: body
        name: real_name
        schema:
          type: string
      - description: 會員性別
        in: body
        name: gender
        schema:
          type: string
      - description: 會員生日
        in: body
        name: birthday
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 更新會員資料
      tags:
      - 會員
  /auth:
    get:
      consumes:
      - application/json
      description: 登入驗證
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
        "500":
          description: desc
          schema:
            $ref: '#/definitions/models.JSONResult'
      summary: 登入驗證
      tags:
      - 驗證
swagger: "2.0"
